import { useState } from 'react';
import { Alert } from 'react-native';
import { signup } from '../services/authService';

export const useSignup = (navigation) => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSignup = async () => {
    if (!name || !email || !password || !confirmPassword) {
      Alert.alert('Error', 'All fields are required.');
      return;
    }

    if (password !== confirmPassword) {
      Alert.alert('Error', 'Passwords do not match.');
      return;
    }

    try {
      setLoading(true);
      const data = await signup(name, email, password);

      if (data.success) {
        // Pass employeeId to OTP screen (generated by backend during signup)
        navigation.navigate('Otp', { employeeId: data.employeeId, email, password, name });
      } else {
        Alert.alert('Signup Failed', data.message);
      }
    } catch (error) {
      Alert.alert('Error', 'Could not connect to server.');
    } finally {
      setLoading(false);
    }
  };

  return {
    name, setName,
    email, setEmail,
    password, setPassword,
    confirmPassword, setConfirmPassword,
    loading,
    handleSignup,
  };
};
